// class Autogenerated {
//   String arleagues;
//   Country country;
//   int countryId;
//   Coverage coverage;
//   int currentSeasonId;
//   int id;
//   String logoPath;
//   String name;
//   Country season;
//   String type;
//
//   Autogenerated({this.arleagues, this.country, this.countryId, this.coverage, this.currentSeasonId, this.id, this.logoPath, this.name, this.season, this.type});
//
//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     arleagues = json['Arleagues'];
//     country = json['country'] != null ? new Country.fromJson(json['country']) : null;
//     countryId = json['country_id'];
//     coverage = json['coverage'] != null ? new Coverage.fromJson(json['coverage']) : null;
//     currentSeasonId = json['current_season_id'];
//     id = json['id'];
//     logoPath = json['logo_path'];
//     name = json['name'];
//     season = json['season'] != null ? new Country.fromJson(json['season']) : null;
//     type = json['type'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['Arleagues'] = this.arleagues;
//     if (this.country != null) {
//       data['country'] = this.country.toJson();
//     }
//     data['country_id'] = this.countryId;
//     if (this.coverage != null) {
//       data['coverage'] = this.coverage.toJson();
//     }
//     data['current_season_id'] = this.currentSeasonId;
//     data['id'] = this.id;
//     data['logo_path'] = this.logoPath;
//     data['name'] = this.name;
//     if (this.season != null) {
//       data['season'] = this.season.toJson();
//     }
//     data['type'] = this.type;
//     return data;
//   }
// }
//
// class Country {
//   Data data;
//
//   Country({this.data});
//
//   Country.fromJson(Map<String, dynamic> json) {
//     data = json['data'] != null ? new Data.fromJson(json['data']) : null;
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     if (this.data != null) {
//       data['data'] = this.data.toJson();
//     }
//     return data;
//   }
// }
//
// class Data {
//   int id;
//   Null imagePath;
//   String name;
//
//   Data({this.id, this.imagePath, this.name});
//
//   Data.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     imagePath = json['image_path'];
//     name = json['name'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['image_path'] = this.imagePath;
//     data['name'] = this.name;
//     return data;
//   }
// }
//
// class Coverage {
//
//
//   Coverage({});
//
// Coverage.fromJson(Map<String, dynamic> json) {
// }
//
// Map<String, dynamic> toJson() {
//   final Map<String, dynamic> data = new Map<String, dynamic>();
//   return data;
// }
// }
//
// class Data {
//   int id;
//   int leagueId;
//   String name;
//
//   Data({this.id, this.leagueId, this.name});
//
//   Data.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     leagueId = json['league_id'];
//     name = json['name'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['league_id'] = this.leagueId;
//     data['name'] = this.name;
//     return data;
//   }
// }
//
// class Autogenerated {
//   String arleagues;
//   Country country;
//   int countryId;
//   Coverage coverage;
//   int currentSeasonId;
//   int id;
//   String logoPath;
//   String name;
//   Country season;
//   String type;
//
//   Autogenerated({this.arleagues, this.country, this.countryId, this.coverage, this.currentSeasonId, this.id, this.logoPath, this.name, this.season, this.type});
//
//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     arleagues = json['Arleagues'];
//     country = json['country'] != null ? new Country.fromJson(json['country']) : null;
//     countryId = json['country_id'];
//     coverage = json['coverage'] != null ? new Coverage.fromJson(json['coverage']) : null;
//     currentSeasonId = json['current_season_id'];
//     id = json['id'];
//     logoPath = json['logo_path'];
//     name = json['name'];
//     season = json['season'] != null ? new Country.fromJson(json['season']) : null;
//     type = json['type'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['Arleagues'] = this.arleagues;
//     if (this.country != null) {
//       data['country'] = this.country.toJson();
//     }
//     data['country_id'] = this.countryId;
//     if (this.coverage != null) {
//       data['coverage'] = this.coverage.toJson();
//     }
//     data['current_season_id'] = this.currentSeasonId;
//     data['id'] = this.id;
//     data['logo_path'] = this.logoPath;
//     data['name'] = this.name;
//     if (this.season != null) {
//       data['season'] = this.season.toJson();
//     }
//     data['type'] = this.type;
//     return data;
//   }
// }